id: webpack-config

info:
  name: webpack config disclosure
  author: ambassify
  severity: info
  description: A lot of web projects use webpack these days to bundle their project to publish it online - this file holds various metadata relevant to the project.
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/webpack.config.js"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "{"

      - type: word
        words:
          - "application/javascript"
          - "text/javascript"
        part: header
        condition: or

      - type: status
        status:
          - 200